


import type { Metadata } from "next";
import { ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import Header from "@/components/Header";
import SideBar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";





export const metadata: Metadata = {
  title: "Pranav's next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider dynamic >
    <html lang="en">
      <body >
        {/*Header*/}
          <Header/> 
          <div className="flex min-h-screen flex-between">
        {/*sidebar */}
        <SideBar/>
          <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">{ children}</div>
          </div>
          <Toaster position="top-center"/>
          </body>
    </html>
    </ClerkProvider>

  );
}
